// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: authService.proto

package auth

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Authentication service

func NewAuthenticationEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Authentication service

type AuthenticationService interface {
	GetImgCaptcha(ctx context.Context, in *ImgCaptchaRequ, opts ...client.CallOption) (*ImgCaptchaResp, error)
	GetSmsCaptcha(ctx context.Context, in *SmsCaptchaRequ, opts ...client.CallOption) (*SmsCaptchaResp, error)
}

type authenticationService struct {
	c    client.Client
	name string
}

func NewAuthenticationService(name string, c client.Client) AuthenticationService {
	return &authenticationService{
		c:    c,
		name: name,
	}
}

func (c *authenticationService) GetImgCaptcha(ctx context.Context, in *ImgCaptchaRequ, opts ...client.CallOption) (*ImgCaptchaResp, error) {
	req := c.c.NewRequest(c.name, "Authentication.GetImgCaptcha", in)
	out := new(ImgCaptchaResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationService) GetSmsCaptcha(ctx context.Context, in *SmsCaptchaRequ, opts ...client.CallOption) (*SmsCaptchaResp, error) {
	req := c.c.NewRequest(c.name, "Authentication.GetSmsCaptcha", in)
	out := new(SmsCaptchaResp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Authentication service

type AuthenticationHandler interface {
	GetImgCaptcha(context.Context, *ImgCaptchaRequ, *ImgCaptchaResp) error
	GetSmsCaptcha(context.Context, *SmsCaptchaRequ, *SmsCaptchaResp) error
}

func RegisterAuthenticationHandler(s server.Server, hdlr AuthenticationHandler, opts ...server.HandlerOption) error {
	type authentication interface {
		GetImgCaptcha(ctx context.Context, in *ImgCaptchaRequ, out *ImgCaptchaResp) error
		GetSmsCaptcha(ctx context.Context, in *SmsCaptchaRequ, out *SmsCaptchaResp) error
	}
	type Authentication struct {
		authentication
	}
	h := &authenticationHandler{hdlr}
	return s.Handle(s.NewHandler(&Authentication{h}, opts...))
}

type authenticationHandler struct {
	AuthenticationHandler
}

func (h *authenticationHandler) GetImgCaptcha(ctx context.Context, in *ImgCaptchaRequ, out *ImgCaptchaResp) error {
	return h.AuthenticationHandler.GetImgCaptcha(ctx, in, out)
}

func (h *authenticationHandler) GetSmsCaptcha(ctx context.Context, in *SmsCaptchaRequ, out *SmsCaptchaResp) error {
	return h.AuthenticationHandler.GetSmsCaptcha(ctx, in, out)
}
